# cache: bundler
language: objective-c

osx_image: xcode10.2
xcode_project: Cleanse.xcodeproj
xcode_scheme: Cleanse
xcode_sdk: iphonesimulator12.2

jobs:
  include:
    - stage: Test
      script: xcodebuild test -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -enableCodeCoverage=YES -destination "platform=iOS Simulator,name=iPad Air 2"
    - stage: Build Sample Project
      script: xcodebuild build -project Examples/CleanseGithubBrowser/CleanseGithubBrowser.xcodeproj -scheme CleanseGithubBrowser -sdk $TRAVIS_XCODE_SDK

before_install:
  - rvm use $RVM_RUBY_VERSION

install: bundle install -j4 --path vendor/bundle --without documentation test development
after_success: bundle exec slather
